version: 2.1

jobs:
  sayhello:
    description: A job that says Hello
    machine: true
    steps:
      - run: echo "Hello World!"
      - run: echo "Bonjour le monde"
  displayFiles:
    description: Une job qui affiche les fichiers
    machine: true
    steps:
      - run: ls -al

workflows:
  monWorkflow:
    jobs:
      - sayhello
      - displayFiles:
          requires:
            - sayhello

         
